Feature/create update delete
step1041/Athena pull request #27
Opened 2017-06-07 05:33 UTC by step1041

This should complete the MVP requirements - Full CRUD is operational. 

Known bug: hover on the outcome selection is visually broken when surrounded by a label. Current develop branch does not have this problem. Probably an issue with either Bootstrap, Ember-Bootstrap, or Ember.

2017-06-07 12:09 UTC, SpyMaster356 commented
For the known bug did you create a new issue for it, so that you can keep track of it?

2017-06-07 12:24 UTC, Zeragamba requested changes

2017-06-07 12:24 UTC, SpyMaster356 commented on client/app/controllers/application.js
> +        saveGameInParent(outcome, rank) {
Instead of *InParent, you could use onSave, onUpdate, and onDelete as this seems to be an event listener design

2017-06-07 12:24 UTC, SpyMaster356 commented on client/app/templates/application.hbs
> +      {{add-game model=model.games saveGameInParent=(action 'saveGameInParent')}}
When using the name onSave, this line could become:

model=model.games onSave=(action 'saveGame')

2017-06-07 12:24 UTC, SpyMaster356 commented on client/app/templates/components/game-table.hbs
> +                    Rank <small>(After match)</small>
Needs indenting

2017-06-07 12:24 UTC, SpyMaster356 commented on client/app/templates/components/game-table.hbs
> +                    Outcome
Needs indenting

2017-06-07 12:24 UTC, SpyMaster356 commented on server/controllers/gamesController.js
> +      }));
What about returning 404s?

2017-06-07 12:24 UTC, SpyMaster356 commented on server/controllers/gamesController.js
> +      }));
By that I mean, what happens when the record is not found, but isn't a server side error?

2017-06-08 04:11 UTC, step1041 commented
There, I think those commits cover everything. Variable names were cleaned up a bit, although the code in applicaton.hbs needs to be kept the way it is with saveGame=(action 'saveGame') matching.

2017-06-08 10:45 UTC, Zeragamba requested changes

2017-06-08 10:45 UTC, SpyMaster356 commented on server/controllers/gamesController.js
> +      })}else{
Looks like the brackets here got misaligned

2017-06-08 10:45 UTC, SpyMaster356 commented on server/controllers/gamesController.js
> +          throw {
Why not just respond to the request here instead of throwing?

2017-06-08 10:46 UTC, SpyMaster356 commented
What happens if the action name differs from the attribute name?

2017-06-08 21:47 UTC, SpyMaster356 commented on server/controllers/gamesController.js
> +            })}else{
wacky brackets here

2017-06-08 21:49 UTC, merged